# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 463c1337277ff14406744b06993fc21c94a4ad391976847dc707e86834945e15f2d4f0aeec84d685a2a177f008d5c88dfc8e78a507933db2b41f94c2a3c9db79

test:
  secret_key_base: a2d5bf8d7d65ce7e26754e92d0b68c6871ec2c5f776f4a1fc786c5426e68aba45f23e8209036b6d6096880ca9bde18d3b7f74a38f53d3be0ccd3c3eff66f4bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
